/*
 * Copyright 2009 Syed Ali Jafar Naqvi
 *
 * This file is part of Java Call Tracer.
 *
 * Java Call Tracer is free software: you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Java Call Tracer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * Lesser GNU General Public License for more details.
 *
 * You should have received a copy of the Lesser GNU General Public License
 * along with Java Call Tracer.  If not, see <http://www.gnu.org/licenses/>.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_test_jni_TestJNI */

#ifndef _Included_com_codeanalyzer_jni_CodeAnalyzerJNI
#define _Included_com_codeanalyzer_jni_CodeAnalyzerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codeanalyzer_jni_CodeAnalyzerJNI
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_calltracer_jni_CallTracerJNI_start
  (JNIEnv *, jobject);

/*
 * Class:     com_codeanalyzer_jni_CodeAnalyzerJNI
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_calltracer_jni_CallTracerJNI_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_codeanalyzer_jni_CodeAnalyzerJNI
 * Method:    printToScreen
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_calltracer_jni_CallTracerJNI_printTrace
  (JNIEnv *, jobject);

/*
 * Class:     com_codeanalyzer_jni_CodeAnalyzerJNI
 * Method:    flush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_calltracer_jni_CallTracerJNI_flush
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
